Harry's latest init script

diff --git a/piglowd b/piglowd
--- a/piglowd
+++ b/piglowd
@@ -1,6 +1,6 @@
 #! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          skeleton
+# Provides:          Piglow
 # Required-Start:    $all
 # Required-Stop:     $all
 # Default-Start:     2 3 4 5
@@ -9,11 +9,9 @@
 # Description:      Daemon to contol a Piglow board
 ### END INIT INFO
 
-# Author: Harry Moyes  <harry@shoka.net>
+# Piglowd author: Lawrie Griffiths
+# Init script author: Harry Moyes  <harry@shoka.net>
 #
-
-# Do NOT "set -e"
-
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="PiGlow LED board control daemon"
@@ -22,6 +20,7 @@ DAEMON=/usr/bin/$NAME
 DAEMON_ARGS="--options args"
 PIDFILE=/tmp/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
+CONTROLFIFO=/tmp/piglowfifo
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -37,6 +36,17 @@ SCRIPTNAME=/etc/init.d/$NAME
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
+# Initialise the wiringPi i2c functions, once only after boot.
+if [ ! -f "/tmp/piglowinit" ]
+       then 
+       sudo gpio load i2c
+       touch /tmp/piglowinit
+fi
+
+# I prefer piglowd to be in verbose mode. Override the default setting. 
+# Change the following line to no for quiet output or comment out to take the system defaults.
+VERBOSE="yes" 
+
 #
 # Function that starts the daemon/service
 #
@@ -45,18 +55,19 @@ do_start()
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
-	#   2 if daemon could not be started
         start-stop-daemon --status --quiet --pidfile $PIDFILE --name $NAME
         if [ $? -ne 0 ];
         then
           start-stop-daemon --start --quiet --pidfile $PIDFILE \
              --exec $DAEMON --  $DAEMON_ARGS
-	  chmod 666 /tmp/piglowfifo
-          return 0
+	  chmod 666 $CONTROLFIFO
+#	  Make pattern 0 run at start
+          echo 0 > $CONTROLFIFO
+          RETVAL=0
+        else
+          RETVAL=1
         fi
-        # Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+	return "$RETVAL"
 }
 
 #
@@ -67,40 +78,34 @@ do_stop()
 	# Return
 	#   0 if daemon has been stopped
 	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
 	#   other if a failure occurred
         start-stop-daemon --status --quiet --pidfile $PIDFILE --name $NAME
         if [ $? -eq 0 ];
         then        
-          echo x > /tmp/piglowfifo
+          echo x > $CONTROLFIFO
 	  RETVAL=0
         else
           RETVAL=1
         fi
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
 	return "$RETVAL"
 }
 
 #
-# Function that sends a SIGHUP to the daemon/service
+# Function that sends a reload command to the daemon/service
 #
 do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
+	# The daemon can reload its configuration on command
         start-stop-daemon --status --quiet --pidfile $PIDFILE --name $NAME
         if [ $? -eq 0 ]; then        
-           #echo r > /tmp/piglowfifo
-           echo c > /tmp/piglowfifo
+          echo r > $CONTROLFIFO
+#	  Make pattern 0 run at start
+          echo 0 > $CONTROLFIFO
+	  RETVAL=0
+        else
+          RETVAL=1
         fi
-	return 0
+	return "$RETVAL"
 }
 
 case "$1" in
@@ -121,40 +126,34 @@ case "$1" in
 	esac
 	;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	[ "$VERBOSE" != no ] && status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
   reload)
-	#log_daemon_msg "Reloading $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$NAME"
 	do_reload
-	#log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+  restart)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
 		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+		case "$?" in  
+		0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		1) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Old process is still running
+		*) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
 		esac
 		;;
 	  *)
-		# Failed to stop
-		log_end_msg 1
-		;;
-	esac
+		[ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	        esac
 	;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	#echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload}" >&2
 	exit 3
 	;;
 esac
 
 :
+
